apiVersion: apps/v1

deploymen

kind: Deployment

devops-proj

metadata:

k8s-demo

name: oggy-web

Kubernetes-

namespace: oggy

Kubernetes-

labels:

app: oggy-web

minikube

spec:

tejesh

replicas: 2

selector:

yamls

matchLabels:

.bash_histor

app: oggy-web

.bash_logou

template:

.bash_profil

metadata:

.bashrc

labels:

I

app: oggy-web

.cshrc

spec:

tcshrc

containers:

name: oggy-container

anaconda-ks

>

image: oggy-web:v1

imagePullPolicy: Never

ports:

Remote monitoring

containerPort: 80
