apiVersion: apps/v1
kind: Deployment

metadata:
  name: oggy-web
  namespace: oggy
  labels:
    app: oggy-web

spec:
  # replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oggy-web
  template:
    metadata:
      labels:
        app: oggy-web
    spec:
      containers:
      - name: oggy-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "200m"

        volumeMounts:
        - name: db-connection
          mountPath: /connection
        - name: db-password
          mountPath: /password
        ports:
        - containerPort: 80
      volumes:
      - name: db-connection
        configMap:
          name: oggy-cm

      - name: db-password
        secret:
          secretName: database-secret
